http:
  middlewares:
    simpleAuth:
      basicAuth:
        users:
        -  'admin:$apr1$UVo6RtsW$A079TecA7I7EL6nFskiQD1'
  routers:
    api:
      rule: Host(`cpi.maciejewski.net`)
      entryPoints:
        - websecure
      middlewares:
        - simpleAuth
      service: api@internal
      # tls:
      #   certResolver: letsencrypt