entryPoints:
  - web:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  - websecure:
    address: '':443'

api:
  dashboard: true

certificatesResolvers:
  lets-encrypt:
    acme:
      email: james.m.maciejewski@gmail.com
      storage: acme.json
      tlsChallenge: {}

providers:
  docker:
    watch: true
    network: web

  file:
    filename: traefik_dynamic.yml

