version: '3.3'
services:
  coredns:
    build: .
    container_name: coredns
    expose:
      - '1053:1053'
      - '1053:1053/udp'
    volumes:
      - .config:/etc/coredns
    ports:
      - '1053:1053'
      - '1053:1053/udp'
    restart: unless-stopped
    labels:
      - coredns
    networks:
      web:
      coredns:
        ipv4_address: 192.168.2.100
    
networks:
  web: # this is our intranet
    external: true
  coredns: # this is for(?) the ad block container - don't actually have this yet
    name: coredns
    ipam:
      config:
        subnet: 192.168.2.0/24
